// 权限常量定义
export const PERMISSIONS = {
  // 项目管理权限
  VIEW_PROJECTS: 'view_projects',
  CREATE_PROJECT: 'create_project',
  EDIT_PROJECT: 'edit_project',
  DELETE_PROJECT: 'delete_project',
  VIEW_PROJECT_DETAIL: 'view_project_detail',
  VIEW_PROJECT_PROGRESS: 'view_project_progress',
  MANAGE_PROJECT_STAGES: 'manage_project_stages',

  // 成果管理权限
  VIEW_ACHIEVEMENTS: 'view_achievements',
  CREATE_ACHIEVEMENT: 'create_achievement',
  EDIT_ACHIEVEMENT: 'edit_achievement',
  VIEW_ACHIEVEMENT_DETAIL: 'view_achievement_detail',
  CREATE_TRANSFER: 'create_transfer',
  VIEW_TRANSFERS: 'view_transfers',

  // 经费管理权限
  MANAGE_FUNDS: 'manage_funds',
  VIEW_FUND_DASHBOARD: 'view_fund_dashboard',
  VIEW_FUND_OVERVIEW: 'view_fund_overview',
  MANAGE_BUDGET: 'manage_budget',
  MANAGE_FUNDING_APPLICATIONS: 'manage_funding_applications',
  CREATE_FUNDING_APPLICATION: 'create_funding_application',
  MANAGE_EXPENDITURES: 'manage_expenditures',
  CREATE_EXPENDITURE: 'create_expenditure',
  MANAGE_REIMBURSEMENTS: 'manage_reimbursements',
  MANAGE_RECEIPTS: 'manage_receipts',

  // 评审管理权限
  VIEW_REVIEWER_DASHBOARD: 'view_reviewer_dashboard',
  VIEW_REVIEW_TASKS: 'view_review_tasks',
  PERFORM_REVIEW: 'perform_review',
  VIEW_REVIEW_HISTORY: 'view_review_history',
  VIEW_REVIEW_DETAIL: 'view_review_detail',

  // 审核管理权限
  VIEW_ASSISTANT_DASHBOARD: 'view_assistant_dashboard',
  VIEW_AUDIT_TASKS: 'view_audit_tasks',
  AUDIT_PROJECTS: 'audit_projects',
  AUDIT_FUNDING: 'audit_funding',
  AUDIT_ACHIEVEMENTS: 'audit_achievements',
  AUDIT_EXPENDITURES: 'audit_expenditures',

  // 系统管理权限
  VIEW_ADMIN_DASHBOARD: 'view_admin_dashboard',
  MANAGE_USERS: 'manage_users',
  MANAGE_ALL_PROJECTS: 'manage_all_projects',
  SYSTEM_CONFIG: 'system_config',
  VIEW_SYSTEM_LOGS: 'view_system_logs',
  VIEW_ALL_REPORTS: 'view_all_reports',

  // 通用权限
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_PROFILE: 'view_profile',
  VIEW_NOTIFICATIONS: 'view_notifications',
  VIEW_REPORTS: 'view_reports',
}

// 角色权限映射
export const ROLE_PERMISSIONS = {
  APPLICANT: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.EDIT_PROJECT,
    PERMISSIONS.VIEW_PROJECT_DETAIL,
    PERMISSIONS.VIEW_PROJECT_PROGRESS,
    PERMISSIONS.MANAGE_PROJECT_STAGES,
    PERMISSIONS.VIEW_ACHIEVEMENTS,
    PERMISSIONS.CREATE_ACHIEVEMENT,
    PERMISSIONS.EDIT_ACHIEVEMENT,
    PERMISSIONS.VIEW_ACHIEVEMENT_DETAIL,
    PERMISSIONS.CREATE_TRANSFER,
    PERMISSIONS.VIEW_TRANSFERS,
    PERMISSIONS.MANAGE_FUNDS,
    PERMISSIONS.VIEW_FUND_DASHBOARD,
    PERMISSIONS.VIEW_FUND_OVERVIEW,
    PERMISSIONS.MANAGE_BUDGET,
    PERMISSIONS.MANAGE_FUNDING_APPLICATIONS,
    PERMISSIONS.CREATE_FUNDING_APPLICATION,
    PERMISSIONS.MANAGE_EXPENDITURES,
    PERMISSIONS.CREATE_EXPENDITURE,
    PERMISSIONS.MANAGE_REIMBURSEMENTS,
    PERMISSIONS.MANAGE_RECEIPTS,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  REVIEWER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REVIEWER_DASHBOARD,
    PERMISSIONS.VIEW_REVIEW_TASKS,
    PERMISSIONS.PERFORM_REVIEW,
    PERMISSIONS.VIEW_REVIEW_HISTORY,
    PERMISSIONS.VIEW_REVIEW_DETAIL,
    PERMISSIONS.VIEW_PROJECT_DETAIL,
    PERMISSIONS.VIEW_ACHIEVEMENT_DETAIL,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  ASSISTANT: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ASSISTANT_DASHBOARD,
    PERMISSIONS.VIEW_AUDIT_TASKS,
    PERMISSIONS.AUDIT_PROJECTS,
    PERMISSIONS.AUDIT_FUNDING,
    PERMISSIONS.AUDIT_ACHIEVEMENTS,
    PERMISSIONS.AUDIT_EXPENDITURES,
    PERMISSIONS.VIEW_PROJECT_DETAIL,
    PERMISSIONS.VIEW_ACHIEVEMENT_DETAIL,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ADMIN_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ALL_PROJECTS,
    PERMISSIONS.SYSTEM_CONFIG,
    PERMISSIONS.VIEW_SYSTEM_LOGS,
    PERMISSIONS.VIEW_ALL_REPORTS,
    PERMISSIONS.VIEW_PROJECT_DETAIL,
    PERMISSIONS.VIEW_ACHIEVEMENT_DETAIL,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,
    // 管理员拥有所有权限
    ...Object.values(PERMISSIONS),
  ],
}

// 权限检查工具函数
export const checkPermission = (userPermissions, requiredPermission) => {
  return userPermissions.includes(requiredPermission) || userPermissions.includes('admin') // 管理员有所有权限
}

// 获取角色对应的权限
export const getPermissionsByRole = (role) => {
  return ROLE_PERMISSIONS[role] || []
}
